### PR TITLE
Update serialization-arrays.md to correctly explain how to serialise collections

### PR DESCRIPTION
**Pull request by CianNoonanUnity**
**Select the type of change:**

- [x] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

Serialising a nullable collection (System.Array etc) is unsupported. NativeArray/NativeList etc must be used instead. The documentation as it stands is suggesting the user implement unsupported types in their serializable data resulting in confusion.

**Issue Number:** 

https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/2051

### CODE REVIEW

**Comment by CianNoonanUnity** [comment]
There are aspects of this page that I feel likely need to be changed as they also showcase using a nullable collection, however I do not feel I have a good enough understanding of the API to be the one to edit this more complex page: https://docs-multiplayer.unity3d.com/netcode/current/advanced-topics/serialization/inetworkserializable

**Comment by CianNoonanUnity** [comment]
Hey Luke, I've filed this based on a Support query we had. The customer posted a github issue here: https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/issues/2051

**Comment by CianNoonanUnity** [comment]
Thanks for confirming that there are two cases to be considered. I'm happy for my PR to be amended or closed and superseded by another PR that is more complete

**Comment by s-omeilia-unity** [comment]
This doc hasn't been reviewed yet by the current Doc Audit, but will circle back when a more complete review of this doc is being worked on. :)

**Comment by s-omeilia-unity** [comment]
Closing this PR because it will be addressed in the future with some more info detailed in INetworkSerializable's Audit Form. Noting this PR and comments there.

The pages have otherwise been looked over by @NoelStephensUnity.

**Pull request closed without merging**
