### PR TITLE
Add missing steps for NetworkObject

### PR DESCRIPTION
**Pull request by giraffesyo**
**Select the type of change:**

- [x] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

If the Network Object component is not added first the player won't work, with errors in console.  Additionally, since  `HelloWorldPlayer` is referenced from within the `HelloWorldManager` code, I added a note that both steps need to be followed before continuing.

### CODE REVIEW

**Comment by lkrell** [comment]
@Briancoughlin You are currently working in these files. Is this covered, needed for your work?

**Comment by Briancoughlin** [comment]
I have changed the Hello World Part to requirements to indicate that you must have completed the Hello World One to completed part two. ( this is a change from recommending that you complete it) the Network Object component is added in Hello World One. I'm not sure about the other note, We dont tell anyone to build and run the game until the last steps i.e. after you have completed all the steps so this warning seems little overkill to me.
Associated JIRA https://jira.unity3d.com/browse/MTTDOC-267

**Comment by Briancoughlin** [comment]
Work on this is being carried out in the following branch

https://github.com/Unity-Technologies/com.unity.multiplayer.docs/tree/MTTDOC-244-Modularising-Golden-Path-to-enable-better-user-experience.

Closing #208 should let us close this as well

**Comment by giraffesyo** [comment]
Awesome, it's good to know that you guys are actively working on this documentation. We can close this out since it looks like some changes are already coming down the pipeline. Cheers!

**Pull request closed without merging**
