### PR TITLE
update: remove InstanceId, PrefabHash and PrefabHashGenerator

### PR DESCRIPTION
**Pull request by MFatihMAR**
**Select the type of change:**

- [x] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

we no longer have `InstanceId`, `PrefabHash` and `PrefabHashGenerator` fields.
we replaced them with `GlobalObjectIdHash` which is not visible to users over public APIs.
therefore, we should get rid of them in docs to keep things up-to-date.

**Issue Number:** 

MTT-610 & MTT-611

### CODE REVIEW

**Comment by Briancoughlin** [comment]
Quick question has the code been updated so the API sections wont be added back at the next generation step?

**Comment by MFatihMAR** [comment]
> Quick question has the code been updated so the API sections wont be added back at the next generation step?

no, they will never come back :)

**Comment by lkrell** [comment]
@MFatihMAR important questions:
This content is generated by docfx processing into markdown from the 0.1.0 release.
Are these fields in 0.1.0? If so they must remain in the docs. 
Are these changes updated in develop branch? We are planning on cutting a new versioning for develop, and numbered releases.

**Comment by MFatihMAR** [comment]
@lkrell — they were there in `0.1.0` release but they are no longer available on `develop` branch and will never be back in `1.0.0-pre` release.

I'm not sure how you folks are planning to do docs versioning aligned with SDK versions.
However, I'm always happy to follow your guides.
Let us know when you figure out the versioning plan for docs.

**Comment by lkrell** [comment]
Awesome ok we are working on a develop branch strategy :D Don't close this PR yet, will use it to verify the changes against creation of the new branching strategy. :)

**Comment by lkrell** [comment]
Closing PR - all work in master through #185

**Pull request closed without merging**
