### PR TITLE
Upgrades to Docusaurus v2.4

### PR DESCRIPTION
**Pull request by antoniancu**
- - -
**Select the type of change:**

- [ ] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [x] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

Upgrades to stable Docusaurus release v2.3.1
**Issue Number:**

Currently builds fine, but the menu still has issues.
- [ ] Menu link for Release Notes, API or Documentation (without the version) results in a 404
- [ ] Admonitions need swizzling to customize the icon

### CODE REVIEW

**Comment by chrispope** [comment]
Please ensure this upgrade is targeting the develop branch and is tested locally

**Comment by s-omeilia-unity** [comment]
Got local build issue: ValidationError: "docs.sidebar" is not allowed

Will try again tomorrow. Could be because different yarn.lock files between your updated version and my current. 🤷‍♀️

**Comment by armstrongl** [comment]
> Got local build issue: ValidationError: "docs.sidebar" is not allowed
> 
> Will try again tomorrow. Could be because different yarn.lock files between your updated version and my current. 🤷‍♀️

I ran into the same issue. It seems like they changed how you specify the [trailingSlash](https://docusaurus.io/docs/api/docusaurus-config#trailingSlash) configuration option between the beta version we're on and v2.3.1. Now it's a top-level config option and applies globally.

```js
module.exports = {
    title: 'Unity Multiplayer Networking',
    trailingSlash: true,
    tagline: 'Build multiplayer games in Unity',
// ...
```

**Comment by antoniancu** [comment]
You get that error because you were still using outdated npm packages. Once you pull, especially if it's a pre-existing repo on local, make sure to run yarn install. It will upgrade the version specified in the new lock file, and install some new dependencies that were need and i've added. 

My automatic github notifs by email get ignored a lot, feel free to ping me on slack or @ me in a message to escalate visibility.

**Comment by s-omeilia-unity** [comment]
Figured as much. Will run again before our meeting. :)

**Review by s-omeilia-unity — APPROVED** [review]

**Pull request merged**
