### PR TITLE
fix issue #974 (and #965 whoops) (correct mppm link)

### PR DESCRIPTION
**Pull request by 11BelowStudio**
#### **WARNING**: Please make your PR against the `develop` branch.
- - -
**Select the type of change:**

- [ ] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [x] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

fixing mppm link

**Issue Number:**

~~#974~~ #965

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=975) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=975) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=975) it.</sub>

**Comment by armstrongl** [comment]
This issue was addressed in another PR :)

**Comment by 11BelowStudio** [comment]
> This issue was addressed in another PR :)

No, it wasn't.

Click on the 'Multiplayer Play Mode' link in the 'tip' box at the top of the page here https://docs-multiplayer.unity3d.com/netcode/current/tutorials/command-line-helper/index.html, you'll see that it's still broken @armstrongl

**Comment by armstrongl** [comment]
Hi @11BelowStudio. My apologies - I was told this was fixed. If I recall correctly, there's an odd bug with Docusarus that's causing this internal link to behave strangely.

**Comment by 11BelowStudio** [comment]
No, the problem is that the link specified in `docs/tutorials/command-line-helper.md` is just incorrect.

Currently, the link is `[Multiplayer Play Mode package](../../tools/mppm.md)`, sending the user to https://docs-multiplayer.unity3d.com/netcode/tools/mppm.md (a 404 page).

This PR changes it to `[Multiplayer Play Mode package](../../tools/current/mppm)`, sending the user to https://docs-multiplayer.unity3d.com/tools/current/mppm (not a 404 page)

**Comment by s-omeilia-unity** [comment]
@11BelowStudio Using a relative link with "current" does not work because that denotes the doc version.

../../tools/mppm.md works in IDE but doesn't work on local, develop, or prod

../../tools/current/mppm doesn't work in any environment

This is a funky problem when referencing between our separate sections that sometimes just doesn't work out properly. I'm doing a relative no-no by hardcoding this link for the time being. Hardcoding should otherwise be avoided. There are some internal doc changes in the coming months 🤞 that will resolve this type of issue.

Tested against local
Testing against develop before pushing to prod

**Pull request merged**
