### PR TITLE
Update workflow-client-server.md

### PR DESCRIPTION
**Pull request by Wanfanel**
for unity.transport 0.6.0-preview.7
"var writer" was not working, needed use in "out"
"default(NetworkConnection)" change to "default"
one missing csharp tag for style code

**Select the type of change:**

- [x] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

**Issue Number:**

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=177) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=177) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=177) it.</sub>

**Comment by lkrell** [comment]
@LukeStampfli  @Cosmin-B  would like a bit of verification on this one if you have a chance. Thanks!

**Comment by lkrell** [comment]
I'll handle the conflicts before merging when approved.

**Comment by s-omeilia-unity** [comment]
PR appears to have been merged back in Sept but kept open. Closing.

**Pull request closed without merging**
