### PR TITLE
update: adding documentation for PR-2906

### PR DESCRIPTION
**Pull request by NoelStephensUnity**
**For NGO v1.10.0 and v2.0.0-exp.3**

Adding documentation for PR-2906:
https://github.com/Unity-Technologies/com.unity.netcode.gameobjects/pull/2906

#### **WARNING**: Please make your PR against the `develop` branch.
- - -
**Select the type of change:**

- [ ] Small Changes - Typos, formatting, slight revisions
- [X] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**
Adding some documentation on new `NetworkBehaviour` methods.

**Issue Number:**
[MTT-8470](https://jira.unity3d.com/browse/MTT-8470)

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=1260) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=1260) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: Vic-Cooper<br/>:white_check_mark: jabbacakes<br/>:x: NoelStephensUnity<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=1260) it.</sub>

**Review by jabbacakes — COMMENTED** [review]
Have left some comments on the new content. Gonna have a read through of the linked PR and see if there's any additional info I think needs adding.

**Comment by jabbacakes** [comment]
@NoelStephensUnity That review ended up taking a bit longer than usual. Tl;dr, I've split the NetworkBehaviour page out into two: one for spawning and despawning, and one for synchronizing and serialization. Having it all on one page was getting to be _a lot_.

Lemme know what you think.

**Comment by NoelStephensUnity** [comment]
> @NoelStephensUnity That review ended up taking a bit longer than usual. Tl;dr, I've split the NetworkBehaviour page out into two: one for spawning and despawning, and one for synchronizing and serialization. Having it all on one page was getting to be _a lot_.
> 
> Lemme know what you think.

I like it! 👍

**Review by jabbacakes — APPROVED** [review]

**Pull request merged**
