### PR TITLE
MTT-4369 Update UTP documentation to 2.0 documentation structure

### PR DESCRIPTION
**Pull request by johann-r-unity**
**Select the type of change:**

- [ ] Small Changes - Typos, formatting, slight revisions
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

First step toward UTP 2.0.0 documentation ([MTT-3871](https://jira.unity3d.com/browse/MTT-3871))
! **This is preparation work - should be only deployed on staging at the moment**!
- Create the UTP version 2.0.0 
- Updated the side bar to reflect the changes and new features  [Google doc](https://docs.google.com/document/d/1Fz8fC0NePdfuGDoVVFUueFTTW_0BNJ3GZMUidESyV7M/edit#)
- Created place holder files for future work 
- Currently copied API files from 1.X to 2.X , they could be removed if it's easier to start from scratch.

From 

image

to 

image

**Issue Number:** 

MTT-4369 to enable ([MTT-3871](https://jira.unity3d.com/browse/MTT-3871))

### CODE REVIEW

**Comment by simon-lemay-unity** [comment]
There are a few `.bak` files part of this PR. I don't think those were intended to be included.

**Comment by simon-lemay-unity** [comment]
I don't know what the standard is for casing titles in Unity documentation (@s-omeilia-unity do you know?), but currently it's inconsistent even within the documentation. We have titles missing a leading capital letter ("migrating from 1.x.x", "network settings"), some with title case ("Custom Pipeline", "Getting Started"), and some with sentence case ("Use pipelines", "Secure client and server").

**Comment by s-omeilia-unity** [comment]
@simon-lemay-unity Yes, the standards have adjusted a couple times, but this is the current standard for titles in docs: https://docs-style-guide.unity.com/format/titles-and-headers

Basically, it's sentence case, present tense, and not using gerunds.

When it comes to drafting docs, I care more about the filename, doc id, and folder structure at first because that is what generates the URL at publish. Changing those later causes indexing issues (especially with Google) and breaks links. We can update and fix the visible doc titles all day long and it won't break anything.

Going through this PR right now though to see what we have now that the audit is basically done.

**Comment by s-omeilia-unity** [comment]
Ugh, it wasn't supposed to fully merge and close. Reopened for continued work.

**Pull request merged**
