### PR TITLE
Origin/wm goldenpath suggest

### PR DESCRIPTION
**Pull request by will-mearns**
**Select the type of change:**

- [X] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**
I went through the Golden Path tutorial and noted my experience from the perspective of a hobbyist game designer and noted a few things I stumbled on. Use it as you wish :)

**Issue Number:**

### CODE REVIEW

**Comment by will-mearns** [comment]
My commits contained feedback as well*

**Comment by lkrell** [comment]
Just pushed master updates and updated the 0.1.0 version with these same edits.

**Review by lkrell — APPROVED** [review]
Looks good to me! Brian is working on these files and assigned himself, so letting him finalize.

**Comment by Briancoughlin** [comment]
these changes have now been replicated in the #208  PR

**Comment by Briancoughlin** [comment]
this work has been completed in PR #208

**Pull request closed without merging**
