### PR TITLE
Tools 2.0.0 release content

### PR DESCRIPTION
**Pull request by s-omeilia-unity**
#### **WARNING**: Please make your PR against the `develop` branch.
- - -
**Select the type of change:**

- [ ] Small Changes - Typos, formatting, slight revisions
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

**Issue Number:**

### CODE REVIEW

**Review by s-omeilia-unity — COMMENTED** [review]
Updates look good to me!

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=1095) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=1095) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=1095) it.</sub>

**Comment by Vic-Cooper** [comment]
Cut version 2.1.0 and removed 2.0.0 in [this PR](https://github.com/Unity-Technologies/com.unity.multiplayer.docs/pull/1147).

**Comment by jabbacakes** [comment]
Outdated PR, closing.

**Pull request closed without merging**
