### PR TITLE
UTP 2.0 API documentation

### PR DESCRIPTION
**Pull request by armstrongl**
This PR adds the latest API documentation for UTP 2.0.

It also fixes some issues with the Transport drop-down menu and sets UTP 2.0 as the latest release.

### CODE REVIEW

**Comment by simon-lemay-unity** [comment]
I noticed that some of the API documentation is from the `Unity.Netcode.Transports.UTP.UnityTransport` namespace. Is that on purpose? This namespace is provided by the NGO package (`com.unity.netcode.gameobjects`), and not the transport one (`com.unity.transport`).

**Comment by armstrongl** [comment]
> I noticed that some of the API documentation is from the `Unity.Netcode.Transports.UTP.UnityTransport` namespace. Is that on purpose? This namespace is provided by the NGO package (`com.unity.netcode.gameobjects`), and not the transport one (`com.unity.transport`).

@simon-lemay-unity if those aren't supposed to be there, I can remove them :)

**Comment by simon-lemay-unity** [comment]
> Should I remove all the new files prefixed with `Unity.Netcode.`?

Yes, I think so. At least for anything under the `transport/api` folder.

**Comment by armstrongl** [comment]
@simon-lemay-unity I removed the Netcode APIs. Does everything else look good?

**Comment by simon-lemay-unity** [comment]
Everything looks good to me, but I believe @johann-r-unity had mentioned leaving 1.0 as the current release until 2.0 is pre-release. I think we want to keep pointing users at the 1.0 documentation by default until we've polished the 2.0 documentation.

**Pull request closed without merging**
