### PR TITLE
Update object-spawning.md

### PR DESCRIPTION
**Pull request by binaerbaum**
**Select the type of change:**

- [x] Small Changes - Typos, formatting, slight revisions
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site and Docusaurus

**Purpose of the Pull Request:**

Fix typo + broken link to Object Visibility

**Issue Number:**

### CODE REVIEW

**Comment by unity-cla-assistant** [comment]
[CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=152) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=152) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/com.unity.multiplayer.docs?pullRequest=152) it.</sub>

**Comment by lkrell** [comment]
@binaerbaum  I can merge this PR when you have signed the CLA. See the link above to review and accept the terms. Thanks!

**Comment by binaerbaum** [comment]
> @binaerbaum I can merge this PR when you have signed the CLA. See the link above to review and accept the terms. Thanks!

Hi :)

I checked the CLA. If it were just giving some details of my github account I would gladly do it.
However  having to give my full name, address and phone number just to update some documentation seems to me a bit much to ask :) Is it really necessary to collect so much information ?

Since I am not comfortable giving up all that information, feel free to cherry pick / amend the commits.

Next time I'll create an issue :)

**Comment by lkrell** [comment]
Sure thing, sorry about that! Oh that is a ton of info to request. I'll check further into it. :)

**Comment by binaerbaum** [comment]
Thanks :) that would be really appreciated !

**Pull request merged**
